# CDC pipeline example.
http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: "/rpcn"

input:
  http_server:
    path: /cdc

pipeline:
  processors:
    - noop: {}

# output:
#   stdout: {}
output:
  broker:
    pattern: fan_out
    outputs:
      - kafka:
          addresses:
            - redpanda-0:9092
          topic: trades
          client_id: trades_consumer_grp
          key: ""
      - stdout: {}


logger:
  level: INFO
  format: json

metrics:
  prometheus: {}
